
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.8"

install:
  # Ensure modern pip/etc to avoid some issues w/ older worker environs
  - pip install -U pip

  - pip install -e .
  # Dev (doc/test running) requirements
  # TODO: use pipenv + whatever contexty-type stuff it has
  - pip install codecov # For codecov specifically
  - pip install -r ./api/requirements.txt
script:
  # Fast syntax check failures for more rapid feedback to submitters
  # (Travis-oriented metatask that version checks Python, installs, runs.)
  - inv travis.blacken
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
  # All (including slow) tests, w/ coverage!
  - inv coverage
  # Ensure documentation builds, both sites, maxxed nitpicking
  - inv sites
notifications:
  email: true
after_success:
  - codecov